
graphql:
  endpoint:
    url: http://localhost:8182/graphql


#We don't need the web server to start (it would start due to e the Spring reactive dependencies)
spring:
  main:
    web-application-type: none
