server:
  port: 8181

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: TRACE

spring:
  security:
#    user:
#      name: "user"
#      password: "password"
#      roles:
#        - "USER"
    oauth2:
      authorizationserver:
        issuer: http://localhost:8181
        client:
          graphql-oauth2:
            registration:
              client-id: "login-client"
              client-secret: "{noop}openid-connect"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/login-client"
                - "http://127.0.0.1:8080/authorized"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
          login-client-with-messaging:
            registration:
              client-id: "login-client-with-messaging"
              client-secret: "{noop}with-messages"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/login-client-with-messaging"
                - "http://127.0.0.1:8080/authorized"
              scopes:
                - "openid"
                - "profile"
                - "message:read"
                - "message:write"
            require-authorization-consent: true
          messaging-client:
            registration:
              client-id: "clientId"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorized"
              scopes:
                - "message:read"
                - "message:write"
            require-authorization-consent: true