# Changing the port for the GraphQL server
server:
  port: 8180

security:
  enable:
    csrf: false # This should probably not be done in production

spring:
  graphql:
    schema:
      locations: classpath*:graphql_schema/**/ 

    # Changing the server path
    http:
      path: /my/updated/graphql/path
    # Both activating the web socket support and overriding the default path
    websocket:
      path: /my/updated/graphql/path

    # Enabling graphiql (from spring-graphql)
    graphiql:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181


